defaults:
- arxiv_v4-32_base
- _self_

num_hosts: 4

mesh:
  d: 16
  t: 1

training:
  warmup_steps: 650 
  steps:        6500
  steps_for_lr: 6500
  learning_rate: 1.0e-3
  token1:
    batch: 256

model:
  d_model: 512
  n_q_per_kv: 1
  n_kv: 8
  d_head: 128
  layers: 8
  d_ff: 4096
  vocab: 32768
  rope_max_timescale: 10000
  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true
  base:
    d_model: 256 
    n_q_per_kv: 1
    n_kv: 16 
    d_head: 64
    d_ff: 2048
  
checkpoint_interval: 9200
